#ifndef MACRO_H
#define MACRO_H

#define COMMAND_LENGTH 100
#define SPECIAL_INPUT_LENGTH 200

#define ESCKEY 3
#define FRUIT_NAME_LENGTH 50

#define FRUIT_PRODUCT_SIZE 5
#define MEAT_PRODUCT_SIZE 5

#define PLAYER_PRODUCT_SIZE 4
#define STARTING_MONEY 50

#define ERROR_PURCHASING 404

#define FILE_EXIST 105
#define FILE_NOT_EXIST 110
#endif
